# Generated by Django 4.2.5 on 2023-09-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='message',
        ),
        migrations.AlterField(
            model_name='contactme',
            name='subject',
            field=models.TextField(),
        ),
    ]
