# Generated by Django 4.2.5 on 2023-09-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_contactme_message_alter_contactme_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
